#!/bin/bash
if [ $# -eq 0 ]
  then
    echo -e "\e[31mNo engine name supplied\e[0m"
    exit 1
fi

# current path
APP_PATH=`pwd`

# check engine exists
for var in "$@"    
do
    exist=false
    while IFS='' read -r line || [[ -n "$line" ]]; do
        if [ "$line" == "gem 'erp_$var', path: 'engines/$var'" ]; then
            exist=true
        fi
    done < "$APP_PATH/Gemfile"
    
    if $exist ; then
        if [ -d "$APP_PATH/engines/$var" ]; then
            echo -e "\e[31mEngine '$var' exists\e[0m"
            continue
        fi
    fi
    
    # insert to Gemfile
    echo "gem 'erp_$var', path: 'engines/$var'" >> "$APP_PATH/Gemfile"
    cd "$APP_PATH/engines"
    
    # convert _ to - for git repositories
    git_name=$var
    for i in {1..10}      
    do
      git_name=${git_name/_/-}
    done
    
    # clone into engine folder
    # git clone "http://github.com/mrhungton/erp-$git_name" "$var"
    git clone "http://github.com/globalnaturesoft-erp/erp-$git_name" "$var"
    cd "$var"
    git checkout develop
    
    echo -e "\n\e[32mEngine '$var' installed\e[0m\n"
done

# bundle install
cd "$APP_PATH"
bundle install

# run migrate
rails db:migrate

echo -e "\n\e[32mEngine(s) installed\e[0m"
    
